class ProductOptionType < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  acts_as_list scope: :product
  # relationships .............................................................
  belongs_to :product, inverse_of: :product_option_types
  belongs_to :option_type, inverse_of: :product_option_types
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

