class ProductProperty < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :product, touch: true, inverse_of: :product_properties
  belongs_to :property, inverse_of: :product_properties
  # validations ...............................................................
  validates :property, presence: true
  # TODO
  # validates_with Spree::Validations::DbMaximumLengthValidator, field: :value
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order(:position) }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
