class Taxonomy < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_many :taxons, inverse_of: :taxonomy
  has_one :root, -> { where parent_id: nil }, dependent: :destroy
  # validations ...............................................................
  validates :name, presence: true
  # callbacks .................................................................
  after_create :set_root
  after_save :set_root_taxon_name
  # scopes ....................................................................
  default_scope { order("position, created_at") }
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  private

  def set_root
    self.root ||= Taxon.create!(taxonomy_id: id, name: name)
  end

  def set_root_taxon_name
    root.update_attributes(name: name)
  end
end




