class Taxon < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  acts_as_nested_set dependent: :destroy
  # relationships .............................................................
  belongs_to :taxonomy, inverse_of: :taxons
  has_many :classifications, -> { order(:position) }, dependent: :delete_all, inverse_of: :taxon
  has_many :products, through: :classifications
  # has_and_belongs_to_many :prototypes
  # validations ...............................................................
  validates :name, presence: true
  validates :meta_keywords, length: { maximum: 255 }
  validates :meta_description, length: { maximum: 255 }
  validates :meta_title, length: { maximum: 255 }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
