class Variant < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  # includes ..................................................................
  # include Spree::DefaultPrice
  # relationships .............................................................
  belongs_to :product, touch: true, inverse_of: :variants

  has_and_belongs_to_many :option_values
  # validations ...............................................................
  validates_uniqueness_of :sku, allow_blank: true, conditions: -> { where(deleted_at: nil) }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
