class Variant < ActiveRecord::Base
  # extends ...................................................................
  acts_as_paranoid
  # includes ..................................................................
  # include Spree::DefaultPrice
  # relationships .............................................................
  belongs_to :product, touch: true, inverse_of: :variants
  has_and_belongs_to_many :option_values

  has_many :prices, dependent: :destroy, inverse_of: :variant
  # validations ...............................................................
  validates_uniqueness_of :sku, allow_blank: true, conditions: -> { where(deleted_at: nil) }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # delegate_belongs_to :product, :name, :description, :slug, :available_on,
  #                   :shipping_category_id, :meta_description, :meta_keywords,
  #                   :shipping_category
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
